# Generated by Django 3.1.7 on 2021-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(choices=[('USA', 'United State of America'), ('RO', 'Romania')], default=('USA', 'United State of America'), max_length=3, verbose_name='country'),
        ),
    ]
