# Generated by Django 3.1.7 on 2021-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='', max_length=10, verbose_name='rated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=3, verbose_name='country'),
        ),
    ]
