# Generated by Django 3.1.7 on 2021-04-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210414_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='boxoffice',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbid',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbvotes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='metascore',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
