# Generated by Django 3.1.7 on 2021-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210414_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.PositiveBigIntegerField(default=0, verbose_name='boxoffice'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.PositiveBigIntegerField(default=0, verbose_name='dvd'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbvotes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='imdbvotes'),
        ),
    ]
