# Generated by Django 3.1.7 on 2021-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210416_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='boxoffice'),
        ),
    ]
