# Generated by Django 3.1.7 on 2021-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210416_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='awards'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='models'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='imdbid'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbvotes',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='imdbvotes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(default='', null=True, verbose_name='plot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='production'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='rated'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='released'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0, null=True, verbose_name='runtime'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=75, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='writer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0, null=True, verbose_name='year of appearance'),
        ),
    ]
