# Generated by Django 3.1.7 on 2021-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210416_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.PositiveBigIntegerField(default=0, null=True, verbose_name='dvd'),
        ),
    ]
