# Generated by Django 3.1.7 on 2021-04-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210416_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.CharField(max_length=255, null=True, verbose_name='released'),
        ),
    ]
