# Generated by Django 3.1.7 on 2021-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20210416_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(default=0, null=True, verbose_name='metascore'),
        ),
    ]
