# Generated by Django 3.1.7 on 2021-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20210416_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='dvd'),
        ),
    ]
