# Generated by Django 3.1.7 on 2021-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20210416_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.IntegerField(default=0, null=True, verbose_name='dvd'),
        ),
    ]
